-- TODO: refactor to support new public.money_account

-- CREATE FUNCTION super.sanitize_document_money_transactions(
--     dry_run boolean
-- ) RETURNS SETOF public.document_money_transaction AS
-- $$
-- DECLARE
--     document_money_transaction RECORD;
-- BEGIN
--     CREATE TEMPORARY TABLE incorrectly_matched_document_money_transactions ON COMMIT DROP AS (
--         SELECT dbt.* FROM public.document_money_transaction AS dbt
--             INNER JOIN (
--                 public.bank_transaction AS bt
--                 INNER JOIN public.bank_account AS ba ON (ba.iban = bt.bank_account_iban)
--             ) ON (bt.id = dbt.bank_transaction_id)
--             INNER JOIN public.document AS d ON (d.id = dbt.document_id)
--         WHERE (
--             d.company_id <> ba.company_id
--         )
--     );

--     IF NOT COALESCE(dry_run, false) THEN
--         FOR document_money_transaction IN (SELECT * FROM incorrectly_matched_document_money_transactions) LOOP
--             DELETE FROM public.document_money_transaction AS dbt WHERE (
--                 dbt.document_id = document_money_transaction.document_id
--             ) AND (
--                 dbt.bank_transaction_id = document_money_transaction.bank_transaction_id
--             );
--         END LOOP;
--     END IF;

--     RETURN QUERY SELECT * FROM incorrectly_matched_document_money_transactions;
-- END;
-- $$
-- LANGUAGE plpgsql VOLATILE;
