services:
  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "127.0.0.1:${LOCALSTACK_PORT-4566}:9000"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - MINIO_REGION=${AWS_DEFAULT_REGION}
    healthcheck:
      test: ["CMD-SHELL", "mc ready local"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER" ]
      timeout: 1s
      interval: 1s
      retries: 5
    ports:
      - "127.0.0.1:${POSTGRES_PORT-5432}:5432"
