-- CREATE FUNCTION api.invoice_item_mutation()
-- RETURNS trigger AS
-- $$
-- DECLARE
--     input RECORD;
-- BEGIN
--     input := COALESCE(NEW, OLD);

--     IF NOT EXISTS (SELECT 1 FROM api.invoice WHERE (id = input.invoice_document_id)) THEN
--         RAISE EXCEPTION 'Document "%" not found', input.invoice_document_id;
--     END IF;

--     CASE TG_OP
--         WHEN 'INSERT' THEN
--             INSERT INTO public.invoice_item (
--                 id,
--                 document_id,
--                 pos_nr,
--                 unit,
--                 title,
--                 description, 
--                 product_nr,
--                 ean_nr,
--                 gtin_nr,
--                 quantity,
--                 unit_net_price,
--                 discount_percent,
--                 vat_name,
--                 vat_percent
--             ) VALUES (
--                 input.id,
--                 input.invoice_document_id,
--                 input.pos_nr,
--                 input.unit,
--                 input.title,
--                 input.description,
--                 input.product_nr,
--                 input.ean_nr,
--                 input.gtin_nr,
--                 input.quantity,
--                 input.unit_net_price,
--                 input.discount_percent,
--                 input.vat_name,
--                 input.vat_percent
--             );

--             RETURN input;
--         WHEN 'DELETE' THEN
--             IF NOT EXISTS (SELECT 1 FROM api.invoice_item WHERE (id = input.id)) THEN
--                 RAISE EXCEPTION 'InvoiceItem "%" not found', input.id;
--             END IF;

--             DELETE FROM public.invoice_item WHERE (id = input.id);

--             RETURN input;
--         WHEN 'UPDATE' THEN
--             IF NOT EXISTS (SELECT 1 FROM api.invoice_item WHERE (id = input.id)) THEN
--                 RAISE EXCEPTION 'InvoiceItem "%" not found', input.id;
--             END IF;

--             UPDATE public.invoice_item
--                 SET
--                     document_id=input.invoice_document_id,
--                     pos_nr=input.pos_nr,
--                     unit=input.unit,
--                     title=input.title,
--                     description=input.description,
--                     product_nr=input.product_nr,
--                     ean_nr=input.ean_nr,
--                     gtin_nr=input.gtin_nr,
--                     quantity=input.quantity,
--                     unit_net_price=input.unit_net_price,
--                     discount_percent=input.discount_percent,
--                     vat_name=input.vat_name,
--                     vat_percent=input.vat_percent,
--                     updated_at=now()
--             WHERE (id = input.id);

--             RETURN input;
--     END CASE;
-- END;
-- $$
-- LANGUAGE plpgsql SECURITY DEFINER;

-- CREATE TRIGGER api_invoice_item_mutation_trigger INSTEAD OF INSERT OR DELETE OR UPDATE
--     ON api.invoice_item
--     FOR EACH ROW
--     EXECUTE PROCEDURE api.invoice_item_mutation();

-- ----

-- CREATE FUNCTION api.create_invoice_item(
--     pos_nr              text,
--     title               text,
--     quantity            float8,
--     unit_net_price      float8,
--     invoice_document_id uuid = NULL,
--     unit                text = NULL,
--     description         text = NULL,
--     product_nr          text = NULL,
--     ean_nr              text = NULL,
--     gtin_nr             text = NULL,
--     discount_percent    float8 = NULL,
--     vat_name            text = NULL,
--     vat_percent         float8 = NULL
-- ) RETURNS api.invoice_item AS
-- $$
--     INSERT INTO api.invoice_item (
--         id,
--         pos_nr,
--         title,
--         quantity,
--         unit_net_price,
--         invoice_document_id,
--         unit,
--         description, 
--         product_nr,
--         ean_nr,
--         gtin_nr,
--         discount_percent,
--         vat_name,
--         vat_percent
--     ) VALUES (
--         uuid_generate_v4(),
--         create_invoice_item.pos_nr,
--         create_invoice_item.title,
--         create_invoice_item.quantity,
--         create_invoice_item.unit_net_price,
--         create_invoice_item.invoice_document_id,
--         create_invoice_item.unit,
--         create_invoice_item.description, 
--         create_invoice_item.product_nr,
--         create_invoice_item.ean_nr,
--         create_invoice_item.gtin_nr,
--         create_invoice_item.discount_percent,
--         create_invoice_item.vat_name,
--         create_invoice_item.vat_percent
--     )
--     RETURNING *
-- $$
-- LANGUAGE SQL VOLATILE;

-- COMMENT ON FUNCTION api.create_invoice_item IS 'Creates an `InvoiceItem`.';

-- ----

-- CREATE FUNCTION api.delete_invoice_item(
--     id uuid
-- ) RETURNS api.invoice_item AS
-- $$
--     DELETE FROM api.invoice_item WHERE (id = delete_invoice_item.id) RETURNING *
-- $$
-- LANGUAGE SQL VOLATILE;

-- COMMENT ON FUNCTION api.delete_invoice_item IS 'Deletes an `InvoiceItem`.';

-- ----

-- CREATE FUNCTION api.update_invoice_item(
--     id                  uuid,
--     pos_nr              text,
--     title               text,
--     quantity            float8,
--     unit_net_price      float8,
--     invoice_document_id uuid = NULL,
--     unit                text = NULL,
--     description         text = NULL,
--     product_nr          text = NULL,
--     ean_nr              text = NULL,
--     gtin_nr             text = NULL,
--     discount_percent    float8 = NULL,
--     vat_name            text = NULL,
--     vat_percent         float8 = NULL
-- ) RETURNS api.invoice_item AS
-- $$
--     UPDATE api.invoice_item
--         SET
--             pos_nr=update_invoice_item.pos_nr,
--             title=update_invoice_item.title,
--             quantity=update_invoice_item.quantity,
--             unit_net_price=update_invoice_item.unit_net_price,
--             invoice_document_id=update_invoice_item.invoice_document_id,
--             unit=update_invoice_item.unit,
--             description=update_invoice_item.description,
--             product_nr=update_invoice_item.product_nr,
--             ean_nr=update_invoice_item.ean_nr,
--             gtin_nr=update_invoice_item.gtin_nr,
--             discount_percent=update_invoice_item.discount_percent,
--             vat_name=update_invoice_item.vat_name,
--             vat_percent=update_invoice_item.vat_percent
--     WHERE (id = update_invoice_item.id)
--     RETURNING *
-- $$
-- LANGUAGE SQL VOLATILE;

-- COMMENT ON FUNCTION api.update_invoice_item IS 'Updates an `InvoiceItem`.';
